include::../../docs/asciidoc/settings.adoc[]

:toc:

== {course-1}

=== Inhalte

*Setup*:

- [ ] IDE (IntelliJ & Visual Studio Code), Java (Installation, etc. ...)
- [ ] Test-Driven-Development
- [ ] Unit-Tests mit JUnit

*Theorie & Objektmodell*:

- [ ] Klassen & Objekte
- [ ] Objektvertrag (hashCode, equals)
- [ ] Vererbung & Interfaces
- [ ] Abstrakte Klassen
- [ ] Beziehungsarten (Besitz, Aufruf, Vererbung, ...), Aggregation vs. Komposition etc.
- [ ] Referenzsemantik

=== Fachlicher Kontext
----
Vorbereitung: Darstellung des fachlichen Kontextes

 + Überwachungssystem in der Betriebsleitung

 + Zug, Zugtypen, Triebfahrzeug (Tbf), Wagons
 + Streckennetz

 + Fahrplan

 + Störung, Weichenausfall, Abfahrt, Ankunft (z.B. verspätete Ankunft im Bahnhof)
 + Dispositionsmaßnahme (z.B. Umleitung)
----

Zur Erläuterung:

image::diagrams/business-model.svg["Fachbegriffe",width="75%",align="center"]

=== Technisches Setup

*Klassenmodell* erzeugen:

----
 + Zug (Zugarten), Wagons (Wagonarten)
 + Strecke, Abschnitt, Gleis
 + Ereignisse: Abfahrt, Ankunft
 + Fahrt

 (+ Dispositionsmaßnahme, Umleitung)
----

Überblick über das grundsätzliche *Fachklassenmodell*:

[plantuml, "Klassenmodell", png, align="center"]
....
include::diagrams/business-model.puml[]
....

Das Interface `Train` sieht dabei wie folgt aus:

[source, java, linenums]
----
include::{course-1-src}/model/train/Train.java[lines=5..13]
----

Für mehr Einblicke in das Modell und die Objekterzeugung, siehe auch

 test/de/dhbw/course1/model/ModelTest.java

=== Objektvertrag (object contract)

The Object class defines both the `equals()` and `hashCode()` methods, which means that these two methods are implicitly defined in every Java class, even if they are not implemented explicitly.

The default implementation of `equals()` in the Object class says that *equality* is the same as object *identity*.

[source, java, linenums, title="Gleich oder Identisch?"]
----
include::{course-1-test}/basics/BasicsTest.java[tag="object-contract-1"]
----

[source, java, linenums, title="Gleich oder Identisch?"]
----
include::{course-1-test}/basics/BasicsTest.java[tag="object-contract-2"]
----


=== Reference Semantics

*Example 1*: "_pass by value_"

In the *pass by value* concept, the method is called by passing a value. The argument is a copy of the original one. This is called 'pass by value'. It does not affect the original parameter.

[source, java, linenums, title="Reference Sematics Bsp. mit Primitiven"]
----
include::{course-1-test}/basics/BasicsTest.java[tags="ref-semantics-prim"]
----

image::diagrams/reference-semantics-prim.svg["RefSemPrim",width="50%",align="center"]


*Example 2*: "_pass reference and update its' state_"

Although the argument variable is passed in, the reference itself is copied. The object that is really referenced is still the same and can thus be changed!

[source, java, linenums, title="Reference Semantics Bsp. mit Objekten"]
----
include::{course-1-test}/basics/BasicsTest.java[tags="ref-semantics-obj"]
----

image::diagrams/reference-semantics-obj.svg["RefSemObj",width="50%",align="center"]


// ---------------------- HIDDEN ----------------------
.Click to reveal details for *Example 3*: "_pass by reference_"
[%collapsible]
====
*Example 3*: "_pass by reference_"

In the *pass by reference* concept, the method is called using an alias or reference of the actual parameter. This is called pass by reference. It forwards the unique identifier of the object to the method. If we make changes to the parameter's instance member, it would affect the original value.

CAUTION: [red]#_Java does not support pass by reference concept!_#

//[subs="normal"]
//----
//include::{course-1-test}/basics/BasicsTest.java[tags="ref-semantics-2"]
//----
====
// ---------------------- HIDDEN ----------------------


Ein weiteres Beispiel für *Reference Semantics*:

image::diagrams/reference-semantics.svg["RefSem",width="100%",align="center"]

[cols="^1,9a", grid="none", frame="none"]
|===
| # | Erläuterung/Kommentar

| [yellow]#(1)#
| Erzeugung einer Variable `a1` vom Typ `Account` mit Zuweisung zur neuen Instanz sowie der Initialisierung des Attributes `amount` mit dem Wert `0`

[source,java]
----
include::{course-1-test}/basics/BasicsTest.java[lines="69"]
----

| [yellow]#(2)#
| Aus Sicht der Methode `process(Account acc)` wird eine Variable `acc` definiert, sie hat initial den Wert `null`

[source,java]
----
include::{course-1-src}/basics/refsemantics/Account.java[lines="22"]
----

| [yellow]#(3)#
| Beim Aufruf der Methode `process(a1)` wird der Wert bzw. die "Adresse" der Variable `a1`  nach `acc` kopiert (_"copy-by-value"_)

//include::{course-1-test}/basics/BasicsTest.java[lines="73"]
[source]
----
        Account.process(a1)
----


| [yellow]#(4)#
| Hier wird (einfach) eine neue Instanz `a2` von `Account` angelegt, sie hat zunächst nichts mit den vorhergehenden Dingen zu tun. Bei dieser zweiten Instanz wird das Attribut `amount` allerdings gleich dem Wert `100` initialisiert

[source,java]
----
include::{course-1-src}/basics/refsemantics/Account.java[lines="24"]
----

| [yellow]#(5)#
| Bei der Zuweisung von `acc = a2` wird die Referenz auf die neue Instanz "gelenkt"

[source,java]
----
include::{course-1-src}/basics/refsemantics/Account.java[lines="25"]
----

| [yellow]#(6)#
| Hier wird der interne Status der Instanz von `Account`, nämlich der Attributwert von `amount` um `250` erhöht, der Objektzustand wird also verändert!

[source,java]
----
include::{course-1-src}/basics/refsemantics/Account.java[lines="27"]
----

|===



=== Übungen


Übungsaufgabe 1::
Erzeuge ein kleines Klassenmodell aus dem folgenden Anwendungsfall:

-> _"Ein Bahnhof besteht aus einer Wartehalle und Bahnsteigen mit je mindestens 1 oder 2 Gleisen. Bahnhöfe werden zudem nach Fern- und Regionalbahnhöfen differenziert."_


Übungsaufgabe 2::
Versuche "Reference Semantics" grafisch zu erläutern!
