include::../../docs/asciidoc/settings.adoc[]

:toc:

== {course-1}

=== Inhalte

_Setup_:

* IDE (IntelliJ & Visual Studio Code), Java (Installation, etc. ...)
* Test-Driven-Development
* Unit-Tests mit JUnit

_Theorie & Objektmodell_:

. Klassen & Objekte
. Objektvertrag (hashCode, equals)
. Vererbung & Interfaces
. Abstrakte Klassen
. Beziehungsarten (Besitz, Aufruf, Vererbung, ...), Aggregation vs. Komposition etc.
. Referenzsemantik

=== Fachlicher Kontext
----
Vorbereitung: Darstellung des fachlichen Kontextes

 + Überwachungssystem in der Betriebsleitung

 + Zug, Zugtypen, Triebfahrzeug (Tbf), Wagons
 + Streckennetz

 + Fahrplan

 + Störung, Weichenausfall, Abfahrt, Ankunft (z.B. verspätete Ankunft im Bahnhof)
 + Dispositionsmaßnahme (z.B. Umleitung)
----

Zur Erläuterung:

image::diagrams/business-model.svg["Fachbegriffe",width="75%",align="center"]

=== Technisches Setup

*Klassenmodell* erzeugen:

----
 + Zug (Zugarten), Wagons (Wagonarten)
 + Strecke, Abschnitt, Gleis
 + Ereignisse: Abfahrt, Ankunft
 + Fahrt

 (+ Dispositionsmaßnahme, Umleitung)
----

Überblick über das grundsätzliche *Fachklassenmodell*:

[plantuml, "Klassenmodell", png, align="center"]
....
include::diagrams/business-model.puml[]
....

Das Interface `Train` sieht dabei wie folgt aus:

[subs="normal"]
----
include::{course-1-src}/model/train/Train.java[lines=5..13]
----

=== Reference Semantics

*Example 1*: "_pass by value_"

In the *pass by value* concept, the method is called by passing a value. The argument is a copy of the original one. This is called 'pass by value'. It does not affect the original parameter.

[subs="normal"]
----
include::{course-1-test}/basics/BasicsTest.java[tags="ref-semantics-1"]
----

image::diagrams/reference-semantics-prim.svg["RefSemPrim",width="50%",align="center"]


*Example 2*: "_pass reference and update its' state_"

Although the argument variable is passed in, the reference itself is copied. The object that is really referenced is still the same and can thus be changed!

[subs="normal"]
----
include::{course-1-test}/basics/BasicsTest.java[tags="ref-semantics-3"]
----

image::diagrams/reference-semantics-obj.svg["RefSemObj",width="50%",align="center"]


// ---------------------- HIDDEN ----------------------
.Click to reveal details for *Example 3*: "_pass by reference_"
[%collapsible]
====
*Example 3*: "_pass by reference_"

In the *pass by reference* concept, the method is called using an alias or reference of the actual parameter. This is called pass by reference. It forwards the unique identifier of the object to the method. If we make changes to the parameter's instance member, it would affect the original value.

CAUTION: [red]#_Java does not support pass by reference concept!_#

//[subs="normal"]
//----
//include::{course-1-test}/basics/BasicsTest.java[tags="ref-semantics-2"]
//----
====
// ---------------------- HIDDEN ----------------------


=== Übungen


Übungsaufgabe 1::
Erzeuge ein kleines Klassenmodell aus dem folgenden Anwendungsfall:

-> _"Ein Bahnhof besteht aus einer Wartehalle und Bahnsteigen mit je mindestens 1 oder 2 Gleisen. Bahnhöfe werden zudem nach Fern- und Regionalbahnhöfen differenziert."_


Übungsaufgabe 2::
Versuche "Reference Semantics" grafisch zu erläutern!
