include::settings.adoc[]

== How To's


=== Setup IntelliJ IDE

to be done


=== Duplicate a new IntelliJ module on the base of another module

Follow these steps to create a new module in an IntelliJ project, here for example `Programmierung-II-W3WI-109`. Created module shall be named `course-2` as an example, using the settings of `course-1`:

. Open project dialog:

 File > Project Structure ...

. Select project modules in the dialog:

 Project Settings > Modules

. Add a new module using the `+` sign, specify a unique name, for example `course-2`.

. Accept settings as proposed by clicking `Create`. The new module now appears in the project view!

. Open the `iml` file from `course-1.iml` as the source for settings. Copy the full file contents simply into the previously created new module file, here `course-2.iml`. Save and exit.

. Optional: Simply copy `/src` and maybe also `/test` directories if you want to have existing code in the new module.

The new module now has (code and) settings of the source module!


=== Setup VSCode IDE

Basic *setup* steps:

. Open `VSCode` on your local machine
. Use `Explorer` to open your local Java workspace, e.g.

 <path-to-your-root-dir>/Programmierung-II-W3WI-109

. You should now see all "course" folders, but let's check required prerequisites & extensions first

. *Java Runtime Environment*, click `Manage > Command Palette` and search & click `Java: Configure Java Runtime`

. If not already selected, choose your locally installed Java (`17`) runtime using the `edit` button under `Java Versions`

NOTE: [small]#Alternatively, edit your `settings.json` file directly by opening menu `Code > Preferences > Settings` and switch to tab `Workspace`, then search for i.e. "_Runtime_" and click on `Java > Configuration: Runtimes` to get to the `settings.json` file. Pay *attention* to the different tabs for "user" and "workspace"!#

[start=6]
. *Extensions*: To get a sophisticated Java environment, extend VSCode with some extensions, the recommended are:

.. Asciidoc
.. Extension Pack for Java, which bundles the following:
... Debugger for Java
... Project Manager for Java
... Test Runner for Java
... Maven for Java
.. IntelliCode
.. Language Support for Java(TM) by RedHat

. Check if *tests* are working simply by executing any unit test file via the `play` button, that is displayed on every unit test class as well as on each of its test methods

. If there are any *compilation* problems, that may be caused by missing *classpath configuration*. To fix this, click `Manage > Command Palette` and search `Java: Configure Classpath`, then add - if not already done - `/src` and `/test` folders of each course module.

NOTE: [small]#Like above, see also the file `.vscode/settings.json` that shows which classpath entries to add, so that the modules can "see" code of other modules.#



