include::../../docs/asciidoc/settings.adoc[]

=== Erfahrungsprotokoll & Planung

[cols="^1,^1m,^1m,7e"]
|===
| | PLAN (1) | IST (2) | Inhalt, Kommentar

a| * [x] {nbsp} | 1 | 1 | IDE Setup (Git, IntelliJ, Maven, PlugIns)

a| * [x] {nbsp} | 1 | 1 | Einführung Maven, Projektstruktur & pom

a| * [x] {nbsp} | 1 | 1 | TDD Einführung

a| * [x] {nbsp} | 1 | 1 | Git Einführung & clone project

a| * [x] {nbsp} | 1 | 1 | Klassen & Objekte
a| * [x] {nbsp} | 1 | 1 | Vererbung & Interfaces
a| * [x] {nbsp} | 1 | 1 | abstrakte Klassen

a| * [x] {nbsp} | 1 | 1 | Access Modifier (Sichtbarkeiten, Scopes)

a| * [x] {nbsp} | 1 | 2 | Update Project bzw. git pull

a| * [x] {nbsp} | 1 | 2 | Übung: "Ein erstes Klassenmodell & der erste Unit-Test"

a| * [x] {nbsp} | 1 | 2 | Einführung Objektvertrag (hashCode(), equals())
a| * [x] {nbsp} | - | 2 | NEU: Debugging in der IDE
a| * [x] {nbsp} | 2 | 3 | Übung 1a: "News Klasse" mit "Code Generation" erzeugen. Neu: Konstruktor
a| * [x] {nbsp} | 2 | 3 | Übung 1b: equals() und hashCode()

a| * [ ] {nbsp} | 2 | 3 | Unit-Test Demo: In `BasicsTest` die Wiederholungsübungen durchgehen (Passengers add/remove)

a| * [x] {nbsp} | 2 | 3 | Methoden überladen, überschreiben/übersteuern
a| * [x] {nbsp} | 2 | 3 | Unit-Test Demo: Overload, Override mit "Display"

a| * [x] {nbsp} | 2 | 3 | Collections API Einführung

a| * [x] {nbsp} | (2) | 4 | Einführung Datentypen & Umwandlung
a| * [x] {nbsp} | (2) | 4 | Demo: Datentyp-Umwandlung
a| * [x] {nbsp} | (2) | 4 | Übung 2a+b: Datentyp-Umwandlung

a| * [x] {nbsp} | (2) | 4 | Schlüsselwort "Static"
a| * [x] {nbsp} | (2) | 4 | Demo: Static (Factory) Klasse

a| * [x] {nbsp} | (2) | 4 | Einführung Schleifen
a| * [x] {nbsp} | (2) | 4 | Demo: For-Each-Loop

a| * [x] {nbsp} | (2) | 4 | Wiederholung Klassenmodell
a| * [x] {nbsp} | (2) | 4 | Übung 3: Klassenmodell implementieren und "generate code" nutzen

a| * [x] {nbsp} | 2 | 4 | Wiederholung: Collections Framework
a| * [x] {nbsp} | 2 | 4 | Übung 4a: Eine Liste implementieren und die "for-each-loop" nutzen zur Summierung

4+a|
====
{continue-here}
====

a| * [ ] {nbsp} | 2 | 4 | Übung 4b: Eine SortedMap implementieren und sie Sortierung prüfen

a| * [ ] {nbsp} | 2 | 5 | Theorie: Beziehungsarten (Besitz, Aufruf, Vererbung, ...), Aggregation vs. Komposition
a| * [ ] {nbsp} | 2 | 5 | Demo: OneToOne, OneToMany am Beispiel
a| * [ ] {nbsp} | 2 | 5 | Übung 5: Assoziation mit Kurs und Student:innen

a| * [ ] {nbsp} | 2 | 5 | Theorie: Many-To-Many
a| * [ ] {nbsp} | 2 | 5 | Demo: ManyToMany am Beispiel der n:m Relation (Kurs, Student:innen)
a| * [ ] {nbsp} | 2 | 5 | Übung 6: ManyToMany, Information Hiding

a| * [ ] {nbsp} | 3 | 5 | (*Modul*) Einführung Java Generics
a| * [ ] {nbsp} | 3 | 5 | Demo in Klasse GenericsTest
a| * [ ] {nbsp} | 3 | 5 | Übungen 1 - Calculator
a| * [ ] {nbsp} | 3 | 5 | Übungen 2 - Workflow mit Steps

a| * [ ] {nbsp} | 3 | 5 | (*Modul*) Einführung funktionale Programmierung
a| * [ ] {nbsp} | 3 | 5 | Demo in Klassen LambdaTests und StreamingTests
a| * [ ] {nbsp} | 3 | 5 | Übungen 1 - Lambda Ausdruck
a| * [ ] {nbsp} | 3 | 5 | Übungen 2a+b - for-each "old fashioned" vs. "modern way"
a| * [ ] {nbsp} | 3 | 5 | Übungen 3 (optional) Warenkorb, Gesamtpreis-Kalkulation mit filter-map-reduce Algorithmen

|===
[small]#*(1)* = Thema war ursprünglich geplant für Seminartag `n`, oder "neu eingeführt" mit Klammern `(n)`,
*(2)* = Thema war tatsächlich Inhalt des Seminartags `n`,#
