include::../../docs/asciidoc/settings.adoc[]

:toc:

== {course-6}

*Allgemeine Inhalte*

* [ ] Checked vs. Runtime (unchecked) exceptions
* [ ] Fachliche Exceptions
* [ ] Exception Handling - was ist zu tun?
* [ ] Javadoc - die wichtigsten Regeln
* [ ] Javadoc - Syntax

*Fachlicher Kontext*
----
 + Fach-Exceptions (z.B. InvalidTrainNumberException, DelayedDepartureWarning)
 + Dokumentation des fachlichen Klassenmodells aus den vorangegagenen Beispielen
----

=== Exception Hierarchie

[plantuml, title="Exceptions Hierarchie", png, align="center"]
....
include::diagrams/exceptions-hierarchy.puml[]
....

Throwable::
Die `Throwable` Klasse ist die Superklasse von allen `Errors` oder `Exceptions` innerhalb von Java. Nur Objekte, die Instanzen dieser Klasse oder einer seiner Subklassen sind, werden von der JVM selbst geworfen, durch `throw new` manuell geworfen oder das entsprechende Schlüsselwort `throws` deklariert werden.
Gleichermaßen können nur diese oder ihre Subklassen als Argumenttyp im `catch` Abschnitt genutzt werden.

Die wichtigsten Codefragmente:

[source, java, lines]
----
 public void process() throws ValidationException {
    // code that may throw an exception
 }

 public void process() {
   // code that may throw an exception in
   // a specific situation
   if (!condition) {
     throw new ValidationException();
   }
 }

 try {
     // ...
 } catch (ValidationException ve) {
     // ...
 }
----

Error::
Die `Error` Subklasse zeigt ein "ernstes" Problem an, das eine Applikation nicht "fangen" oder "behandeln" sollte. Die meisten solcher Fehler bilden außergewöhnliche Fehlerbedingungen oder -zustände ab, die (in aller Regel) nicht _zur Laufzeit_ gehoben werden können.

Exception::
Die Klasse `Exception` und dessen Subklassen bilden Situationen im Code ab, die bekannt sind, eintreten könnten und daher "gefangen" und behandelt werden sollten. Tritt eine solche geplante Fehlersituation auf, so sollte der Fehler so behandelt werden, dass die Applikation nicht abgebrochen werden muss. Eine häufige Reaktion auf diese Art von Fehlern münden häufig in Meldungen an die Benutzer einer Anwendung.

Ein *Beispiel*-Klassenmodell:

[plantuml, title="Exceptions Beispiel", png, align="center"]
....
include::diagrams/exceptions-model.puml[]
....


=== Exception Handling

Grundsätzlich stellt Java einen sogenannten `exception handler` bereit, und zwar einfach mithilfe des `catch` Abschnittes. Hier sollte der abgefangene Fehler "behandelt" werden, aber *NICHT* so:

[source, java]
include::{course-6-src}/io/DataLoader.java[tags=exception-handling-1]

Besser ist eine echte Verarbeitung des Fehlers. Hier sind sehr verschiedene Prozesse möglich, anhängig vom eingetretenen Fehler. In vielen Fällen sind bei Fehlern sowohl ...

* _technische_ als auch
* _fachliche_

Dinge zu tun. Dazu kann z.B. ein eigener, applikationsspezifischer `ExceptionHandler` eingesetzt werden, der die Behandlung an eine andere Komponente _delegiert_:

[source, java]
include::{course-6-src}/io/DataLoader.java[tags=exception-handling-2]


=== Dokumentation mit Javadoc

Quellcode sollte dokumentiert werden, allerdings gibt es sehr unterschiedliche Ansichten zu dem Thema. Zunächst kurz die Grundlagen.

Es gibt 3 Arten von Kommentaren:

. `// ...` Single-Line Kommentare
. `/* ... */` Multi-Line Kommentare
. `/** ... */` Javadoc Dokumentationskommentare

Für die dritte Variante gibt es Syntaxregeln zu beachten, weil aus diesen Kommentaren Websites erstellt werden können, die die "offizielle" Dokumentation des Sourcecodes bzw. der API darstellen und insofern allgemein anerkannten Regeln folgen sollten.

Ein paar grundlegende Richtlinien bzgl. der *Javadoc* Dokumentation:

. Die öffentliche API *muss* dokumentiert werden
. Darüber hinaus *sollten* alle Codeteile dokumentiert werden, die für das Verständnis des Codes von besonderer Bedeutung sind
. Private Felder oder Methoden werden *in der Regel nicht* dokumentiert (_es sei denn sie dienen Punkt 2._)
. In Javadoc *sollte* vorrangig die (_fachliche_) Bedeutung der Implementierung dokumentiert werden, weniger die (_technische_) Art und Weise bzw, Umsetzung
. Javadoc sollte mithilfe des Command Line Tools `javadoc` erzeugt werden

Und ein wenig *Best Practices* zu Umsetzung bzw. Syntax:

* Use HTML tags to format the doc, like `<p>, <pre>, <ol>, <strong>` und weitere
* Use `<code>` style for keywords and names
* Use in-line links economically (links for API names using the `{@link}` tag
* Omit parentheses for the general form of methods and constructors
* OK to use phrases instead of complete sentences, in the interests of brevity.
* Use 3rd person (descriptive) not 2nd person (prescriptive).
* Method descriptions begin with a verb phrase
* Class/interface/field descriptions can omit the subject and simply state the object.
* Use "this" instead of "the" when referring to an object created from the current class.
* Add description beyond the API name.

{tbd}