include::../../docs/asciidoc/settings.adoc[]

:toc:

== {course-9}

*Allgemeine Inhalte*

* Design Patterns
** Erzeugungsmuster
** Strukturmuster
** Verhaltensmuster
* Refactoring
** Vorgehensweisen
** Nutzung der IDE

*Fachliche Anwendungsfälle*
----
 - Komplexe Erzeugung von Instanzen von "Zug"
 - Ausgabe von Verspätungsmeldungen in GUIs
 - Nutzung von Kommando's als Stil einer ganzen SW
 - Adapter zur Umwandlung von domänenspezifischen Objekten
 - Beobachtung von Zug-Ereignissen in einer Karte
 - Wahlmöglichkeit für das Format von "Responses"
----

=== Erzeugungsmuster (Creational Patterns)

*Factory*

Versteckt eine komplexe Initialisierung bzw. Erzeugung in Fabrik-Methoden oder -Klassen. Oft in statischer Weise.

[source, java, indent=0]
----
include::{course-9-test}/PatternTest.java[tags="pattern-creation-factory"]
----


=== Strukturmuster (Structural Patterns)

*Decorator (V1)*

Fügt zusätzlich Verantwortlichkeiten einer Klasse hinzu. Geeignet, wenn die genutzte Funktionalität aus Dritt-Bibliotheken kommt und angepasst werden soll.

CAUTION: Kann leicht das _Single-Responsibility-Principle_ aushebeln!

[source, java, indent=0]
----
include::{course-9-test}/PatternTest.java[tags="pattern-structure-decorator-1"]
----

*Decorator (V2)*

[source, java, indent=0]
----
include::{course-9-test}/PatternTest.java[tags="pattern-structure-decorator-2"]
----

*Proxy*

Repräsentiert einen Stellvertreter oder einen Platzhalter für das eigentliche zu nutzende Objekt dar und stellt auf diese Weise einen konktrollierbaren Zugriff auf die darunter liegende Klasse/Objekt bereit.

[source, java, indent=0]
----
include::{course-9-test}/PatternTest.java[tags="pattern-structure-proxy"]
----


=== Verhaltensmuster (Behavioral Patterns)

*Adapter*

Fügt einer Klasse zusätzliche Funktionalität dynamisch (d.h. zur Laufzeit) hinzu. Ist vergleichbar mit "Subclassing", bleibt dabei aber flexibler.

[source, java, indent=0]
----
include::{course-9-test}/PatternTest.java[tags="pattern-behavior-adapter"]
----

*Observer*

Definiert eine 1:n Beziehung zwischen einem Objekt, das seine Zustandsänderung mitteilen möchte und Objekte, die diese Änderungen automatisch konsumieren (beobachten) wollen.

[source, java, indent=0]
----
include::{course-9-test}/PatternTest.java[tags="pattern-behavior-observer"]
----

*Strategy*

Definiert eine Familie von Algorithmen, kapselt diese jeweils in separaten Klassen und macht sie dadruch austauschbar (_pluggable_). Nutzende Klassen sind gegenüber dem Austausch der Algorithmen agnostisch, sie bemerken ihn gar nicht.

[source, java, indent=0]
----
include::{course-9-test}/PatternTest.java[tags="pattern-behavior-strategy"]
----

*Template*

Definiert das _"Skelett"_ eines Algorithmus als Operation (Methode) mit vorgegebenem Ablauf und überlässt die Implementierung den (erbenden) Klassen für die ganze oder auch nur Teile des Algorithmus. Die Struktur des Algorithmus bleibt dabei aber immer gleich.

[source, java, indent=0, indent=0]
----
include::{course-9-test}/PatternTest.java[tags="pattern-behavior-template"]
----


=== Architekturmuster (Architectural Patterns)

*Filter-Chain*

Typisches Architekturmuster, erlaubt die Aneinanderreihung von (in sich geschlossenen) unabhängigen Verarbeitungsschritten mit klaren Ein- und Ausgabewerten.

[source, java, indent=0]
----
include::{course-9-test}/PatternTest.java[tags="pattern-architecture-filter-1"]
----
