include::../../docs/asciidoc/settings.adoc[]


:sectnums!:
:show-answers:


:question-seq: {counter:question-seq}
====
[.big.red]#*Frage {question-seq}*#
====

Welche der folgenden *Listentypen* wäre am passendsten zur Speicherung von Listenelementen geeignet, wenn ein Listenelement nicht mehr als einmal vorkommen darf, und auch der Wert `null` ebenfalls nicht eingefügt werden darf?

----
A. Collection
B. List
C. Set
D. Map
E. Vector
----

[blue]#*Antwort*#:

ifdef::show-answers[]
-> C
endif::[]

{nl}


// -----------------------------------------------------------------
:question-seq: {counter:question-seq}
====
[.big.red]#*Frage {question-seq}*#
====

Welche ist die wichtigste Eigenschaft von `TreeSet`?

----
A. benutzt Schlüsselwerte zur Speicherung von Werten
B. bewahrt die "natürliche" Ordnung der eingefügten Listenelemente
C. gestattet das Hinzufügen eines `null` Elementes
----

[blue]#*Antwort*#:

ifdef::show-answers[]
-> B
endif::[]

{nl}


// -----------------------------------------------------------------
:question-seq: {counter:question-seq}
====
[.big.red]#*Frage {question-seq}*#
====

Was bedeutet *Überladung* (von Methoden)?

----
A. Wenn eine Methode eine Methode der Elternklasse übersteuert
B. Wenn eine Methode mehr als 3 Argumente aufweist
C. Wenn mehrere Methoden gleichen Names existieren, aber mit
   unterschiedlichen Parametern bzw. Parameterlisten
----

[blue]#*Antwort*#:

ifdef::show-answers[]
-> C
endif::[]

{nl}


// >>>>>>>>>>>>>>>>>>>>>>>>> PAGE BREAK <<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<

// -----------------------------------------------------------------
:question-seq: {counter:question-seq}
====
[.big.red]#*Frage {question-seq}*#
====

Java kennt unterschiedliche sogenannte `access modifier`, die den Zugriff bzw. die Sichtbarkeit von Klassen, Datenattributen oder Methoden steuern. Nennen Sie diese und beschrieben Sie kurz deren Bedeutung!

[blue]#*Antwort*#:

ifdef::show-answers[]
 default   = package-private, nur von Klassen im aktuellen
             Paket verfügbar/sichtbar
 public    = von überall verfügbar/sichtbar
 protected = nur in erbenden Klassen verfügbar/sichtbar
 private   = nur innerhalb der eigenen Klasse verfügbar/sichtbar
endif::[]

{nl}
{nl}
{nl}
{nl}
{nl}
{nl}
{nl}
{nl}
{nl}
{nl}


// -----------------------------------------------------------------
:question-seq: {counter:question-seq}
====
[.big.red]#*Frage {question-seq}*#
====


to be done?

----
Options
----

[blue]#*Antwort*#:

